import math
a = int(input('Введите число a: '))
b = int(input('Введите число b: '))
print(f'Сумма = {a + b}')
print(f'Разность = {a - b}')
print(f'Произведение = {a * b}')
print(f'Частное от деления = {a / b}')
print(f'Остаток от деления = {a % b}')
print(f'Десятичный логарифм = {math.log10(a)}')
print(f'Возведение в степень = {a ** b}')